import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "team_member" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"name" varchar NOT NULL,
  	"role" varchar NOT NULL,
  	"image_id" integer NOT NULL,
  	"image_landscape_id" integer NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );

  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "team_member_id" integer;
  ALTER TABLE "team_member" ADD CONSTRAINT "team_member_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "team_member" ADD CONSTRAINT "team_member_image_landscape_id_media_id_fk" FOREIGN KEY ("image_landscape_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "team_member_image_idx" ON "team_member" USING btree ("image_id");
  CREATE INDEX "team_member_image_landscape_idx" ON "team_member" USING btree ("image_landscape_id");
  CREATE INDEX "team_member_updated_at_idx" ON "team_member" USING btree ("updated_at");
  CREATE INDEX "team_member_created_at_idx" ON "team_member" USING btree ("created_at");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_team_member_fk" FOREIGN KEY ("team_member_id") REFERENCES "public"."team_member"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_team_member_id_idx" ON "payload_locked_documents_rels" USING btree ("team_member_id");`)

  for await (const a of team_members) {
    await payload.create({
      collection: 'team-member',
      data: a,
    })
  }
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "team_member" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "team_member" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_team_member_fk";

  DROP INDEX "payload_locked_documents_rels_team_member_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "team_member_id";`)

  for await (const a of team_members) {
    await payload.delete({
      collection: 'team-member',
      where: {
        name: { equals: a.name },
      },
    })
  }
}

const team_members = [
  {
    id: 6,
    name: 'Janet Daniel',
    role: 'Creative Content Writer',
    image: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    image_landscape: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    updatedAt: '2025-10-19T23:40:49.813Z',
    createdAt: '2025-10-19T23:40:49.813Z',
  },
  {
    id: 5,
    name: 'Aziba Ekio',
    role: 'Head of Content',
    image: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    image_landscape: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    updatedAt: '2025-10-19T23:40:27.783Z',
    createdAt: '2025-10-19T23:40:27.783Z',
  },
  {
    id: 4,
    name: 'Miebaka Joshua',
    role: 'Visual Design Lead',
    image: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    image_landscape: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    updatedAt: '2025-10-19T23:40:07.769Z',
    createdAt: '2025-10-19T23:40:07.769Z',
  },
  {
    id: 3,
    name: 'Voke Omonigho',
    role: 'Product Design Lead',
    image: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    image_landscape: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    updatedAt: '2025-10-19T23:39:30.619Z',
    createdAt: '2025-10-19T23:39:20.072Z',
  },
  {
    id: 2,
    name: 'Joel Omehoma',
    role: 'Generalist Designer',
    image: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    image_landscape: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    updatedAt: '2025-10-19T23:37:51.625Z',
    createdAt: '2025-10-19T23:37:51.625Z',
  },
  {
    id: 1,
    name: 'Joseph Owonvwon',
    role: 'Creative Developer',
    image: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    image_landscape: {
      id: 1,
      alt: null,
      caption: null,
      updatedAt: '2025-10-19T23:35:13.443Z',
      createdAt: '2025-10-19T23:35:13.443Z',
      url: '/api/media/file/Avatar.png',
      thumbnailURL: '/api/media/file/Avatar-300x300.png',
      filename: 'Avatar.png',
      mimeType: 'image/png',
      filesize: 20828,
      width: 460,
      height: 460,
      focalX: 50,
      focalY: 50,
      sizes: {
        thumbnail: {
          url: '/api/media/file/Avatar-300x300.png',
          width: 300,
          height: 300,
          mimeType: 'image/png',
          filesize: 23277,
          filename: 'Avatar-300x300.png',
        },
        square: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        small: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        medium: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        large: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        xlarge: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
        og: {
          url: null,
          width: null,
          height: null,
          mimeType: null,
          filesize: null,
          filename: null,
        },
      },
    },
    updatedAt: '2025-10-19T23:37:26.632Z',
    createdAt: '2025-10-19T23:35:37.699Z',
  },
]
